name: Deploy to Amazon EC2

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Image
        run: docker build -t backend .

      - name: Tag Image
        run: |
          docker tag backend:latest ${{ steps.login-ecr.outputs.registry }}/backend-repo:latest

      - name: Push Image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/backend-repo:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ steps.login-ecr.outputs.registry }}/backend-repo:latest

            docker stop my-app || true
            docker rm my-app || true

            docker run -d -p 5000:5000 --name my-app \
              ${{ steps.login-ecr.outputs.registry }}/backend-repo:latest